version: '3.7'

services:
  app:
    image: 'rafavilomar/simple-nestjs:latest'
    container_name: app_backend
    restart: always
    env_file: .env
    ports:
      - 3500:3500
    depends_on:
      - redis
      - postgres
    networks:
      - app_network
    command: npm start

  redis:
    container_name: redis_db
    restart: always
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - app_network

  postgres:
    container_name: postgres_db
    restart: always
    image: postgres:12.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_PG_USERNAME}
      - POSTGRES_PASSWORD=${DB_PG_PASSWORD}
      - POSTGRES_DB=${DB_PG_DATABASE}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
